version: '3.5'
services:
  php-apache-environment:
    image: ardhanika/kuis-ardhanika
    container_name: 3cd3978e54e5
    depends_on:
      - db
    volumes:
      - ./php/src:/var/wwww/html/
    ports:
      - 7000:80
    networks:
      - backend
  
  db:
    container_name: 3cd3978e54e5
    image: ardhanika/kuis-ardhanika
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root21A.
      MYSQL_DATABASE: batiku
    ports: 
      - ${SERVER_PORT_DB:-3307}:3306
    volumes:
      - db:/var/lib/mysql
      - ./batiku.sql:/docker-entrypoint-initdb.d/batiku.sql
    networks:
      - backend

volumes:
  db:

networks:
  backend:
    name: backend-network
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24